[build]
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200
  force = true

